spring.application.name=medico-service
server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/medico_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:brisas123!}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:rednorte-super-secret-key-2025-minimo32chars!!}
jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.cl.duoc.rednorte=DEBUG
logging.level.org.springframework.security=WARN
