spring.application.name=lista-espera-service


# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL

spring.datasource.url=jdbc:postgresql://localhost:5432/rednorte_db
spring.datasource.username=postgres
spring.datasource.password=TU_PASSWORD_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver


# CONFIGURACIÓN JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# CONFIGURACIÓN DEL SERVIDOR

server.port=8080

# CONFIGURACIÓN JWT

jwt.secret=clave_ultra_secreta_rednorte_minimo_256_bits_necesarios_seguridad
jwt.expiration=86400000


# CIRCUIT BREAKER (Resilience4j)

resilience4j.circuitbreaker.instances.listaEsperaService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.listaEsperaService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.listaEsperaService.waitDurationInOpenState=10s